### ISSUE TITLE
Facing issue after 'npm run dev' 

### ISSUE THREAD

**Issue by maantudas91** [ionic-team/ionic-stencil-hn-app#18]
After `npm run dev` I am getting issue like that

> @stencil/starter@0.0.1 dev C:\OFFICE DATA\ionic-stencil-hn-app
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3333
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at Server.listen (net.js:1495:7)
    at Object.<anonymous> (C:\OFFICE DATA\ionic-stencil-hn-app\node_modules\@stencil\dev-server\dist\index.js:88:64)
    at Generator.next (<anonymous>)
    at fulfilled (C:\OFFICE DATA\ionic-stencil-hn-app\node_modules\@stencil\dev-server\dist\index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
[57:52.4]  @stencil/core v0.1.1-0
[57:52.4]  build, app, dev mode, started ...
[57:52.4]  compile started ...
[58:00.7]  compile finished in 8.31 s
[58:01.9]  bundle styles started ...
[58:02.0]  bundle modules started ...
[58:03.5]  bundle styles finished in 1.64 s
[58:08.3]  bundle modules finished in 6.27 s
[58:13.9]  build finished, watching for changes... in 21.46 s

### Nothing showing in browser, Please help

**Comment by Kaikeanaaina** [comment]
i'm getting the same thing lately, it keeps crashing and points to server.listen
